site_name: Git/GitHub User Documentatio
site_url: https://kylepasag.dev #placeholder
theme:
  name: material
  font:
    text: Inter
    code: Roboto Mono
  icon:
    logo: simple/github
  favicon: assets/github.png
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/kyle-pasag/
    - icon: material/web
      link: https://www.kylepasag.dev

copyright: Copright &copy; 2026 Kyle Pasag and Cedrik Melendez