nav:
  - Home: "index.md"
  - Cloning a Repository: "cloning.md"
  - Committing and Pushing Changes: "committing-and-pushing.md"
  - Branching and Merging: "branching-and-merging.md"
  - Resolving Merge Conflicts: "resolving-merge-conflicts.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossary.md"

site_name: Git/GitHub User Documentation
site_url: https://kpasag.github.io/Git-GitHub-User-Documentation/
theme:
  name: material
  font:
    text: Inter
    code: Roboto Mono
  icon:
    logo: simple/github
  favicon: assets/github.png
  features:
    - navigation.sections
    - navigation.footer
    - toc.integrate

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/github
      link: https://github.com/kpasag/Git-GitHub-User-Documentation
      

copyright: Copright &copy; 2026 Kyle Pasag and Cedrik Melendez
